supabase_url = "https://pitbpfgpgcvhzkwltumr.supabase.co"
supabase_anon_key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBpdGJwZmdwZ2N2aHprd2x0dW1yIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY4NDc4MTAsImV4cCI6MjA3MjQyMzgxMH0.s_x8cWWe-DK01F6O1il87DbPeMR2bDsHbIzgSdcpwLM"
admin_pass = "Ger@88158861"

openai_api_key = "sk-..."
openai_model = "gpt-4o-mini"
